In [1]:
import pandas as pd
import numpy as np
import panel as pn
pn.extension('tabulator')

import hvplot.pandas

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
df = pd.read_csv('owid-co2-data.csv')

In [4]:
df.head()

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
0,Afghanistan,1930,AFG,6626142.00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.13,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
1,Africa,1930,NaN,169924067.00,NaN,0.26,0.00,33.70,-2.11,-5.88,...,NaN,4.82,0.00,0.01,0.01,0.00,NaN,NaN,NaN,NaN
2,Africa (GCP),1930,NaN,NaN,NaN,NaN,NaN,33.70,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Aland Islands,1930,ALA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Albania,1930,ALB,995454.00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.03,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN

In [5]:
df.describe()

,year,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,co2_including_luc,co2_including_luc_growth_abs,...,share_global_other_co2,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share
count,25033.00,21491.00,11875.00,18535.00,18231.00,19861.00,18539.00,18349.00,17609.00,17487.00,...,2282.00,22448.00,20240.00,22448.00,22448.00,20240.00,6149.00,6149.00,4259.00,4258.00
mean,1975.45,77142610.06,313393157422.52,11.28,0.08,549.43,7.80,20.87,570.25,7.97,...,17.06,2.16,0.00,0.01,0.02,0.00,771.49,748.58,-9.08,20.48
std,26.52,413583380.20,2325216225999.79,72.92,0.13,2230.22,70.88,803.01,2380.97,103.95,...,30.52,8.83,0.02,0.05,0.08,0.00,3553.43,3488.00,270.68,53.71
min,1930.00,200.00,49980000.00,0.00,0.00,0.00,-1818.47,-100.00,-187.03,-2318.00,...,0.00,-0.21,-0.00,0.00,-0.00,0.00,-186.55,0.01,-2399.52,-98.28
25%,1953.00,386078.00,8310041088.00,0.00,0.00,0.60,-0.01,-1.15,4.89,-1.09,...,0.31,0.01,0.00,0.00,0.00,0.00,8.44,7.03,-3.15,-6.50
50%,1975.00,3495284.00,29264168960.00,0.16,0.03,6.79,0.06,3.36,26.40,0.05,...,1.49,0.08,0.00,0.00,0.00,0.00,38.05,30.60,1.48,8.87
75%,1998.00,13440088.50,131283206144.00,1.50,0.12,73.16,1.24,9.66,112.34,2.56,...,14.51,0.36,0.00,0.00,0.00,0.00,151.15,131.32,9.03,32.95
max,2021.00,7909295104.00,113630171365376.00,1672.59,2.57,37123.85,1859.76,102318.51,41639.84,2246.72,...,100.00,100.00,0.41,1.11,1.61,0.08,49758.23,48116.56,2206.34,607.52

In [6]:
# Replace NaN values with 0 and create gdp per capita column
df = df.fillna(0)
df['gdp_per_capita'] = np.where(df['population']!=0, df['gdp']/ df['population'], 0)

In [7]:
df

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share,gdp_per_capita
0,Afghanistan,1930,AFG,6626142.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.13,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,Africa,1930,0,169924067.00,0.00,0.26,0.00,33.70,-2.11,-5.88,...,4.82,0.00,0.01,0.01,0.00,0.00,0.00,0.00,0.00,0.00
2,Africa (GCP),1930,0,0.00,0.00,0.00,0.00,33.70,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,Aland Islands,1930,ALA,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,Albania,1930,ALB,995454.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.03,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25028,Western Sahara,2021,ESH,565590.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25029,World,2021,0,7909295104.00,0.00,1672.59,0.21,37123.85,1859.76,5.27,...,100.00,0.41,1.11,1.61,0.08,0.00,0.00,0.00,0.00,0.00
25030,Yemen,2021,YEM,32981644.00,0.00,0.66,0.02,12.48,0.34,2.77,...,0.07,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25031,Zambia,2021,ZMB,19473132.00,0.00,0.96,0.05,7.68,0.40,5.43,...,0.22,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25032,Zimbabwe,2021,ZWE,15993525.00,0.00,0.57,0.04,11.30,0.69,6.49,...,0.11,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [8]:
df.columns

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'cement_co2',
       'cement_co2_per_capita', 'co2', 'co2_growth_abs', 'co2_growth_prct',
       'co2_including_luc', 'co2_including_luc_growth_abs',
       'co2_including_luc_growth_prct', 'co2_including_luc_per_capita',
       'co2_including_luc_per_gdp', 'co2_including_luc_per_unit_energy',
       'co2_per_capita', 'co2_per_gdp', 'co2_per_unit_energy', 'coal_co2',
       'coal_co2_per_capita', 'consumption_co2', 'consumption_co2_per_capita',
       'consumption_co2_per_gdp', 'cumulative_cement_co2', 'cumulative_co2',
       'cumulative_co2_including_luc', 'cumulative_coal_co2',
       'cumulative_flaring_co2', 'cumulative_gas_co2', 'cumulative_luc_co2',
       'cumulative_oil_co2', 'cumulative_other_co2', 'energy_per_capita',
       'energy_per_gdp', 'flaring_co2', 'flaring_co2_per_capita', 'gas_co2',
       'gas_co2_per_capita', 'ghg_excluding_lucf_per_capita', 'ghg_per_capita',
       'land_use_change_co2', 'land_use_change_co2_per_capita', 'methane',
       'methane_per_capita', 'nitrous_oxide', 'nitrous_oxide_per_capita',
       'oil_co2', 'oil_co2_per_capita', 'other_co2_per_capita',
       'other_industry_co2', 'primary_energy_consumption',
       'share_global_cement_co2', 'share_global_co2',
       'share_global_co2_including_luc', 'share_global_coal_co2',
       'share_global_cumulative_cement_co2', 'share_global_cumulative_co2',
       'share_global_cumulative_co2_including_luc',
       'share_global_cumulative_coal_co2',
       'share_global_cumulative_flaring_co2',
       'share_global_cumulative_gas_co2', 'share_global_cumulative_luc_co2',
       'share_global_cumulative_oil_co2', 'share_global_cumulative_other_co2',
       'share_global_flaring_co2', 'share_global_gas_co2',
       'share_global_luc_co2', 'share_global_oil_co2',
       'share_global_other_co2', 'share_of_temperature_change_from_ghg',
       'temperature_change_from_ch4', 'temperature_change_from_co2',
       'temperature_change_from_ghg', 'temperature_change_from_n2o',
       'total_ghg', 'total_ghg_excluding_lucf', 'trade_co2', 'trade_co2_share',
       'gdp_per_capita'],
      dtype='object')

In [9]:
df[df['country'] == 'World']

,country,year,iso_code,population,gdp,cement_co2,cement_co2_per_capita,co2,co2_growth_abs,co2_growth_prct,...,share_of_temperature_change_from_ghg,temperature_change_from_ch4,temperature_change_from_co2,temperature_change_from_ghg,temperature_change_from_n2o,total_ghg,total_ghg_excluding_lucf,trade_co2,trade_co2_share,gdp_per_capita
267,World,1930,0,2070596353.00,0.00,35.56,0.02,3934.73,-332.93,-7.80,...,100.00,0.07,0.19,0.26,0.01,0.00,0.00,0.00,0.00,0.00
538,World,1931,0,2088429965.00,0.00,30.93,0.01,3516.94,-417.79,-10.62,...,100.00,0.07,0.19,0.27,0.01,0.00,0.00,0.00,0.00,0.00
809,World,1932,0,2109357892.00,0.00,24.72,0.01,3170.80,-346.14,-9.84,...,100.00,0.07,0.19,0.27,0.01,0.00,0.00,0.00,0.00,0.00
1080,World,1933,0,2131029147.00,0.00,23.87,0.01,3338.35,167.55,5.28,...,100.00,0.07,0.20,0.28,0.01,0.00,0.00,0.00,0.00,0.00
1351,World,1934,0,2152969392.00,0.00,28.54,0.01,3630.76,292.42,8.76,...,100.00,0.07,0.20,0.28,0.01,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23945,World,2017,0,7599822336.00,110430655610880.00,1507.92,0.20,36096.74,572.55,1.61,...,100.00,0.39,1.04,1.51,0.08,48251.88,47031.82,0.00,0.00,14530.69
24216,World,2018,0,7683789824.00,113630171365376.00,1569.22,0.20,36826.51,729.77,2.02,...,100.00,0.40,1.06,1.54,0.08,49368.04,47980.47,-0.00,0.00,14788.30
24487,World,2019,0,7764951040.00,0.00,1617.51,0.21,37082.56,256.05,0.69,...,100.00,0.40,1.08,1.56,0.08,49758.23,48116.56,0.00,0.00,0.00
24758,World,2020,0,7840952832.00,0.00,1637.54,0.21,35264.09,-1818.47,-4.90,...,100.00,0.41,1.09,1.58,0.08,0.00,0.00,0.00,0.00,0.00
25029,World,2021,0,7909295104.00,0.00,1672.59,0.21,37123.85,1859.76,5.27,...,100.00,0.41,1.11,1.61,0.08,0.00,0.00,0.00,0.00,0.00

## CO2 Emission Over Time by Continent

In [10]:
# Make df pipeline interactive
idf = df.interactive()

#Define Panel widgets
year_slider = pn.widgets.IntSlider(name='year slider', start=1960, end=2021, step=5, value=1970)

#Radio buttons for C02 measures
yaxis_co2 = pn.widgets.RadioButtonGroup(
    name='Y axis',
    options=['co2', 'co2_per_capita'],
    button_type='success'
)

In [11]:
continents = ['World','Asia','Africa','Oceania','Europe','Antarctica', 'North America','South America']

co2_pipeline = (
    idf[
        (idf.year <= year_slider) & (idf.country.isin(continents))
    ]
    .groupby(['country', 'year'])[yaxis_co2].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')
    .reset_index(drop=True)
)

In [12]:
co2_table = co2_pipeline.pipe(
    pn.widgets.Tabulator, 
    pagination='remote', 
    page_size=12, 
    sizing_mode='stretch_width'
)
co2_table

In [13]:
co2_plot = co2_pipeline.hvplot(
    x='year', 
    by='country', 
    y=yaxis_co2,
    line_width=2, 
    title="CO2 Emission by Country"
)
co2_plot

## Summary
This line chart presents a historical overview of carbon emissions on different continents from 1960 to 2021. Each continent is represented by a distinct line on the chart, and the y-axis measures the total carbon emissions in metric tons. Over the six-decade period, viewers can observe the changing trends in emissions, identifying which continents have experienced increases, decreases, or stability in their carbon output. This visualization highlights the evolution of carbon emissions on a global scale and can be used to assess the impact of environmental policies and industrialization trends across continents over time.

## CO2 vs GDP Scatterplot

In [14]:
co2_vs_gdp_scatterplot_pipeline = (
    idf[
        (idf.year == year_slider) & (~(idf.country.isin(continents)))
    ]
    .groupby(['country', 'year', 'gdp_per_capita'])['co2'].mean()
    .to_frame()
    .reset_index()
    .sort_values(by='year')
    .reset_index(drop=True)
)

co2_vs_gdp_scatterplot_pipeline

In [15]:
co2_vs_gdp_scatterplot = co2_vs_gdp_scatterplot_pipeline.hvplot(
    x='gdp_per_capita', 
    y='co2',
    by='country',
    size=60,
    kind='scatter',
    alpha=0.75,
    legend=False,
    height=500,
    width=500
)
co2_vs_gdp_scatterplot

## CO2 Sources by Continent Barchart

In [16]:
yaxis_co2_source = pn.widgets.RadioButtonGroup(
    name='Y axis', 
    options=['coal_co2', 'oil_co2', 'gas_co2'], 
    button_type='success'
)

continents_excl_world = ['Asia', 'Oceania', 'Europe', 'Africa', 'North America', 'South America', 'Antarctica']

co2_source_bar_pipeline = (
    idf[
        (idf.year == year_slider) &
        (idf.country.isin(continents_excl_world))
    ]
    .groupby(['year', 'country'])[yaxis_co2_source].sum()
    .to_frame()
    .reset_index()
    .sort_values(by='year')  
    .reset_index(drop=True)
)

In [17]:
co2_source_bar_plot = co2_source_bar_pipeline.hvplot(kind='bar', 
                                                     x='country', 
                                                     y=yaxis_co2_source, 
                                                     title='CO2 source by continent')
co2_source_bar_plot

## Dashboard View

In [21]:
template = pn.template.FastListTemplate(
    title='World CO2 emission dashboard', 
    sidebar=[pn.pane.Markdown("# CO2 Emissions and Climate Change"), 
             pn.pane.Markdown("#### This dashboard highlights the critical link between CO2 emissions and climate change. It signifies the pivotal role of carbon dioxide (CO2) as the primary greenhouse gas responsible for driving climate change. Understanding and addressing CO2 emissions is essential in mitigating the adverse effects of global warming and its impact on the environment, making it a central issue in the fight against climate change."), 
             pn.pane.Markdown("## Settings"),   
             year_slider],
    main=[pn.Row(pn.Column(yaxis_co2, 
                           co2_plot.panel(width=700), margin=(0,25)), 
                 co2_table.panel(width=500)), 
          pn.Row(pn.Column(co2_vs_gdp_scatterplot.panel(width=600), margin=(0,25)), 
                 pn.Column(yaxis_co2_source, co2_source_bar_plot.panel(width=600)))],
    accent_base_color="#58508d",
    header_background="#003f5c",
)
#template.show()
template.servable();